# Use the official MongoDB image
FROM mongo:latest

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=root
ENV MONGO_INITDB_DATABASE=genieacs
ENV MONGO_INITDB_USER=admin
ENV MONGO_INITDB_PASSWORD=admin

# Copy initialization script to the container
COPY init-mongo.js /docker-entrypoint-initdb.d/
